# Generated by Django 2.1 on 2019-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0002_auto_20190119_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
